spring.application.name=devforge

server.port=8080
server.servlet.context-path=/api/v1

spring.datasource.url=jdbc:postgresql://ep-lively-meadow-amrb62ue-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_OZDrP1slkc7p
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.pool-name=DevForgePool

spring.devtools.restart.enabled=true

jwt.secretKey=gj3cvhi4c2iouvihchjchj412ciyucveiu12ciyu2cujihv4i1viev342bkvbj4v3bdjk3kb4k24k562kcdxi906dr08fs;
jwt.expiration-ms=86400000
