spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.flyway.enabled=true
spring.devtools.restart.enabled=false
spring.cache.type=${CACHE_TYPE:redis}
management.endpoint.health.show-details=${ACTUATOR_HEALTH_DETAILS:never}
springdoc.swagger-ui.enabled=${SWAGGER_UI_ENABLED:false}
